name: VertWhitelist
version: ${project.version}
main: dev.vertcode.vertwhitelist.VertWhitelistPlugin
api-version: 1.16
depend: [ VertLibrary ]
authors: [ VertCode ]
description: A global per-server whitelist controllable from anywhere.
website: vertcode.dev
commands:
  whitelist:
    description: Main command for VertWhitelist
    aliases: [ vertwhitelist ]